[io]
#this is a comment
#outputDir is relative to the toml config file
outputDir = "../result"
outputFile = "example"
logDir = "../result/logs"
meshFile = "foo"

[solver]
CFL = 0.9
tEnd = 0.3
quadType = "bar"
quadOrder = 42 
