name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop, new_dose_comp_csd ]

jobs:
  unit_tests:
      runs-on: ubuntu-latest
      container: kitrt/test:latest
      environment: coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      steps:
      - uses: actions/checkout@v2

      - name: Build code
        run: |
          git submodule update --init --recursive
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DBUILD_ML=OFF -DBUILD_CODE_COV=OFF ..
          ninja

      - name: Run unit tests
        run: |
          cd build
          ./unit_tests
          OMP_NUM_THREADS=1 ./unit_tests -r junit > unit_tests_report.xml

      - name: Code coverage
        run: |
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DBUILD_ML=OFF -DBUILD_CODE_COV=ON ..
          cpp-coveralls -r . -b "build/" -i "src/" -i "include/" --exclude "ext/" --gcov-options "\-lp" --verbose
