name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:  
  unit_tests:
      runs-on: ubuntu-latest
      container: kitrt/test:latest

      steps:
      - uses: actions/checkout@v2
      
      - name: Build code
        run: |
          git submodule update --init --recursive
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DBUILD_CODE_COV=ON ..
          ninja

      - name: Run unit tests
        run: |
          cd build
          OMP_NUM_THREADS=1 ./unit_tests -r junit > unit_tests_report.xml

      - name: Code coverage        
        run: |          
          cpp-coveralls -i src -i include -b build/CMakeFiles/KiT-RT.dir/src/