name: C/C++ CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]


jobs:
  docker_loading:
    runs-on: ubuntu-latest
    name: Docker loading
    steps:
    - name: Get the output time
        run: echo "Loadup successful"
      # To use this repository's private action,
      # you must check out the repository
    - name: Docker loading step
        uses: ./ # Uses an action in the root directory
        id: hello
  
      
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "Loadup successful"
      
  unit_tests:
      name: unit_tests
      runs-on: ubuntu-latest

      steps:
      - name: Intro
        run: echo "Starting unit tests"
        
      #- name: unit_testing_step
      #  uses: actions/unit_testing_step@v1
      
      - name: Outro
        run: echo "Unit testing successful"
