name: C/C++ CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]


jobs:
  docker_loading:
    runs-on: ubuntu-latest
    name: Docker loading
    steps:
    - name: Docker loadup
      id: dock1
      uses: actions/hello-world-docker-action@v1
      
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "Loadup successful"
      
  unit_tests:
      name: unit_tests
      runs-on: ubuntu-latest

      steps:
      - name: Intro
        run: echo "Starting unit tests"
        
      #- name: unit_testing_step
      #  uses: actions/unit_testing_step@v1
      
      - name: Outro
        run: echo "Unit testing successful"
