name: C/C++ CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]


jobs:
  docker_loading:
    runs-on: ubuntu-latest
    name: Docker loading
    steps:
      # To use this repository's private action,
      # you must check out the repository
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker loading
      uses: ./ # Uses an action in the root directory
      id: hello

  unit_tests:
      name: unit_tests
      runs-on: ubuntu-latest

      steps:
      - name: Intro
        run: echo "Starting unit tests"
        
      - name: unit_testing
        run: sh test_with_runner.sh
      
      - name: Outro
        run: echo "Unit testing successful"
